version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: corzello
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      mynetwork:
        ipv4_address: 172.19.0.2  # Fixed IP address for MySQL

  app:
    depends_on:
      - mysqldb
    image: ghaithzouaghi/corzello:latest
    restart: on-failure
    ports:
      - "8081:8081"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      mynetwork:
        ipv4_address: 172.19.0.3  # Fixed IP address for the backend app

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Mount your Prometheus config
    ports:
      - "9090:9090"
    networks:
      mynetwork:
        ipv4_address: 172.19.0.4  # Fixed IP address for Prometheus

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    networks:
      mynetwork:
        ipv4_address: 172.19.0.5  # Fixed IP address for Grafana

volumes:
  db:

networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16  # Updated subnet to avoid overlap
