global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'jenkins'
    static_configs:
      - targets: ['http://192.168.50.4:8080']  # Endpoint de Jenkins

  - job_name: 'corzello-backend'
    static_configs:
      - targets: ['http://192.168.50.4:8081']  # Endpoint du backend Corzello
